### ISSUE TITLE
 Module page http.handlers.templates is mostly blank

### ISSUE THREAD

**Issue by TuggyNE** [caddyserver/website#282] opened 2022-11-25 15:35 UTC
The [Description section](https://caddyserver.com/docs/modules/http.handlers.templates#docs), which should have [a substantial introduction to Go templating in general and Caddy's built-ins in particular](https://web.archive.org/web/20220823142003/https://caddyserver.com/docs/modules/http.handlers.templates#docs), is just blank. I can't figure out where the description is pulled from, or what commit might have caused this, since there's no file in this repo that seems to contain it and the commit range including the last good archive.org copy has no changes that seem to involve it.

**Comment by mholt** [comment] 2022-11-26 00:25
Duplicate of #281 and #278.

Sorry for the inconvenience

**Closed as not planned by mholt** 2022-11-26 00:25 UTC
Labels: duplicate

**Comment by mholt** [comment] 2022-11-26 17:49
In the meantime, the content of the docs can be found in the source code:

https://github.com/caddyserver/caddy/blob/762b02789ac0ef79e92de7c58dac19d24a104587/modules/caddyhttp/templates/templates.go#L34-L270
