### ISSUE TITLE
module pages not getting created proper

### ISSUE THREAD

**Issue by willnorris** [caddyserver/website#281] opened 2022-11-21 07:27 UTC
For example, the Description section of https://caddyserver.com/docs/modules/http.handlers.templates is empty, rather than listing all of the template options [like it used to](https://web.archive.org/web/20220602170850/https://caddyserver.com/docs/modules/http.handlers.templates).

**Comment by francislavoie** [comment] 2022-11-21 07:31
Duplicate of https://github.com/caddyserver/website/issues/278. Known issue. Will be fixed with the next release!

**Closed as completed by francislavoie** 2022-11-21 07:31 UTC
Labels: duplicate
